# Generated by Django 4.2.2 on 2023-06-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_color_alter_product_price_alter_size_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSize',
            new_name='ProductVariant',
        ),
    ]
