# Generated by Django 4.2.2 on 2023-06-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productvariantcolor_productvariantsize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ManyToManyField(to='store.color')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariantsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantsize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='ProductVariantColor',
        ),
        migrations.DeleteModel(
            name='ProductVariantSize',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sizes',
            field=models.ManyToManyField(to='store.size'),
        ),
    ]
