# Generated by Django 4.2.2 on 2023-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_available',
            field=models.BooleanField(default=True),
        ),
    ]
