# Generated by Django 4.2.2 on 2023-06-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_colors_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_available',
        ),
    ]
